config/routes.rb
Rails.application.routes.draw do
  resources :friends
  # get 'home/index'
  get 'home/about'
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phont, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
   
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>
</br>

  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>
</br>

  <div class="field form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>
</br>

  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>
</br>

  <div class="field form-group">
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>

</br>
  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
      <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phont %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-outline-secondary" %> 
  <%= link_to "Back to friends", friends_path, class:"btn btn-outline-secondary" %>
</div>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="friends">
  <% @friends.each do |friend| %>
    <%= render friend %>
    <p>
      <%= link_to "Show this friend", friend, class:"btn btn-outline-secondary" %>
    </p>
  <% end %>
</div>

<%= link_to "New friend", new_friend_path, class:"btn btn-secondary"%>

app/views/friends/new.html.erb
<h1>Add New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-outline-secondary" %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Edit Friend", edit_friend_path(@friend),class:"btn btn-outline-secondary" %> 
  <%= link_to "Back to Friends", friends_path, class:"btn btn-outline-secondary" %>
</br></br>
  <%= button_to "Delete Friend", @friend, method: :delete, class:"btn btn-danger"%>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friends App', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Show Friends', friends_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Add Friend', new_friend_path, class: "nav-link"%>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

app/views/home/index.html.erb
<h1>Welcome to Friends App</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ar">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.rtl.min.css" integrity="sha384-dpuaG1suU0eT09tx5plTaGMLBsfDLzUCCUXOY2j/LSvXYuG6Bqs43ALlhIqAJVRb" crossorigin="anonymous">

    <title>Friends App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <%= yield %>
    </div>
    
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    -->
  </body>
</html>